[project]
name = "dlt-advanced-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[cli,duckdb]>=1.10.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
